#!/bin/bash

age=44

if [ "$age" -gt 18 -a "$age" -lt 25 ]
then
echo "Student can write the exam"
else
echo "Student cannot write the exam"
fi
True && True = True
True && False = True
False && True = True
False && False = False
