#!/bin/bash
echo -e "Enter a value"
read value

case $value in

[a-z])
echo "The value $value is in a to z";;
[A-Z])
echo "The value $value is in A to Z";;
[0-9])
echo "The value $value is in 0 to 9";;
?)
echo "The value $value is a speciall character";;
esac
#Check the character the user has entered and print approprite value
