#!/bin/bash

echo -e "Enter the file name \c"
read file_name

if [ -f $file_name ]
then
echo "File found"
if [ -w $file_name ]
then
echo "File is having write permission. Write text below. Ctrl +
cat >> $file_name
fi
else
echo "File not found"
fi
#sh file.sh
#Enter the file name hello.txt
#File found
#File is having write permission. Write text below. Ctrl + D to exit
#Hello world from prodevelopertutorial.co
