#!/bin/bash

echo -e "Enter the file name \c"
read file_name

if [ -f $file_name ]
then
echo "File found"
if [ -w $file_name ]
then
echo "File is having write permission. Write text below. Ctrl +
cat >> $file_name
fi
else
echo "File not found"
fi
