#!/bin/bash

val=5

if [ $val -eq 5 ]
then
echo "The value is equal to 5"
fi
#-x option:
#This option is used to know step by step how your code is executing.
#Consider below simple if statement:
#"sh -x myScript.sh"
# exam -x 
