#!/bin/bash

age=44

if [ "$age" -gt 18 -a "$age" -lt 25 ]
then
echo "Student can write the exam"
else
echo "Student cannot write the exam"
fi
# So if you want to use single bracket use “-a” operator. If you want to use double brackets use “&&” operator.
# In the above if statement “&&” can be replaced by “-a” as shown below:
